# Generated by Django 5.0.3 on 2024-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('option1', '취미'), ('option2', '음식'), ('option3', '프로그래밍')], default='option1', max_length=50),
        ),
    ]
