# Generated by Django 5.0.3 on 2024-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_read_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='last_read_time',
            field=models.DateTimeField(null=True),
        ),
    ]
