# Generated by Django 5.0.3 on 2024-04-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_comment_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.comment'),
        ),
        migrations.DeleteModel(
            name='Recomment',
        ),
    ]
