# Generated by Django 5.0.3 on 2024-04-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_comment_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
